### ISSUE TITLE
회원 관리 기능 구현하기

### ISSUE THREAD

**Issue by kimgt0128** [kimgt0128/security-jwt-honds-on-Spring-boot-3#1]
# 📌Feature Practice
>Security 프레임워크를 활용해 jwt 방식으로 로그인 기능을 구현합니다.   

   

# 📝To-do
- [x] Security 관련 기본 설정
- [x] JWT 발급 & 검증 설정
- [x] 기타 세션 관련 설정

   
# ✏️To-Study
- 스프링 시큐리티의 동작 과정을 공부합니다. 
- HttpServlet의 요청과 SecurityFilterChain의 동작 방식에 대해 공부합니다.
- 로그인, 회원 가입 로직을 구현합니다.
- 스프링에서 기본적으로 제공하는 UserDetails 클래스에 관해 공부합니다.
- JWT 방식 인증에서 AuthenticationManager가 어떻게 동작하는지 이해합니다.
- 특히 세션 방식과 비교하며 JWT를 사용하는 이유를 공부하며 실습합니다.
