### ISSUE TITLE
JWT 보안 적용하기

### ISSUE THREAD

**Issue by kimgt0128** [kimgt0128/security-jwt-honds-on-Spring-boot-3#4]
# 📌Feature Practice
>서버측에서 안전하게 상용자의 JWT를 관리할 수 있도록 보안에 관련된 사항을 적용합니다.

# 📝To-do
---------Access, Refresh Token 발급
- [ ] Refresh Token, Access Token 발급
- [ ] Access Token 필터
- [ ] Refresh Token으로 Access Token 재발급
- [ ] Refresh Rotate
-----------Refresh Token 서버측 저장

------------기타 설정
- [ ] 로그아웃
-----------------추가 보안

   
# ✏️To-Study
- 주로 Access Token, Refresh Token을 어떻게 관리할 지 공부합니다.
- 서버측에서 Refresh Token을 왜 적용해야 하는지 공부합니다.
- 세션 방식과 JWT 방식을 비교하며 왜 JWT방식을 써야 하는지 공부합니다.
