### ISSUE TITLE
JWT 보안 적용하기

### ISSUE THREAD

**Issue by kimgt0128** [kimgt0128/security-jwt-honds-on-Spring-boot-3#5]
# 📌Feature Practice
>기본적인 JWT 방식을 바탕으로 추가 보안을 적용합니다.

   

# 📝To-do
- [x] 다중 토큰 발급 구현
  - access token: 서버측에서 인가를 받기 위한 코드
  - refresh token: access 토큰을 재발급하기 위한 토큰
- [x] Refresh token 구현
  - Reissue: access 재발급 시 Refresh도 재발급
  - Header에 access, Cookie에 refresh를 담아 응답
  - 기타 쿠키에 대한 보안 설정
- [x] 서버측 주도권 강화
  - 유저 로그인시 서버측 DB에 토큰 임시 저장
  - 서버측 토큰으로 유저 검증
  - 유저 로그아웃시 서버측 DB에서 토큰 삭제
- [ ] 만료된 토큰 관리
  - 스케줄러를 통한 관리
  - Redis의 TTL 통한 관리
- [ ] 추가 보안 구상(토큰 탈취에 대한 위험성 낮추기)
  - 다른 기기에서 로그인 시 문자, 메일 등의 알림(모바일 앱 한정)
  - 주기적으로 Refresh Rotate 진행하기

   
# ✏️To-Study
- 서비스별 Refresh와 Access의 주기 설정 방법에 관해 공부합니다.
- 쿠키를 담아 응답할 때, 신경써야 할 보안 설정을 공부합니다.
- Redis를 사용하고 적용하는 방법, TTL 설정을 공부합니다.
- 추가 보안 방법에 대해 공부합니다.
- 실제 서비스에서 사용하는 추가 보안 설정에 대해 공부합니다.(다른 기기에서 로그인 시 알림 전송 등)
